### PR TITLE
issue #368: persist table/index schema in watermark snapshot for IS recovery

### LINKED ISSUE #368: [gke-bench] NPE in BK executor + IS gRPC channel does not recover after rolling IS restart
## Summary

Two related issues observed during a BIGANN 1B GKE benchmark run (2026-04-30):

1. **Recurring NPE in server's BK scheduled executor** — `NullPointerException` thrown from `SingleThreadSafeScheduledExecutorService$SafeRunnable` running a `NeverSuccessfulListenableFutureTask`, with no stack trace (JVM fast-throw). Happening every ~46–60 s throughout the benchmark.

2. **IS gRPC channel does not recover after rolling IS pod restart** — After a rolling helm upgrade of the IS StatefulSet, the server's gRPC channels to the IS pods entered `UNAVAILABLE` (DNS failure during pod termination). The IS pods came back in seconds, registered in ZK, but the server never re-sent the vector index assignment to them. Result: IS ran for 50+ minutes with the commit-log tailer active but **zero vectors indexed**, because it never received the `AssignIndex` gRPC call from the server. A server pod restart was required to restore normal IS operation.

These two bugs may be related: the NPE was already occurring before the IS upgrade (9:15 AM) and continued after (10:07, 10:08 AM). The `NeverSuccessfulListenableFutureTask` label strongly suggests a periodic IS-management or heartbeat task is permanently failing, which may suppress the reconnect/re-assign logic.

---

## Environment

- HerdDB version: `0.30.0-SNAPSHOT`, git commit `fc398e2a0fd`
- Deployment: GKE (Kubernetes), Helm
- IS replicas: 2, `numShards=4`
- Run: BIGANN 1B (`-n 1000000000 -k 10 --batch-size 2000`)

---

### Verbatim log lines (server pod)

Appears repeatedly at ~46–60 s intervals:

```
Apr 30, 2026 9:15:04 AM org.apache.bookkeeper.common.util.SingleThreadSafeScheduledExecutorService$SafeRunnable run
WARNING: Unexpected throwable from task class com.google.common.util.concurrent.MoreExecutors$ScheduledListeningDecorator$NeverSuccessfulListenableFutureTask: null
java.lang.NullPointerException

Apr 30, 2026 9:23:01 AM org.apache.bookkeeper.common.util.SingleThreadSafeScheduledExecutorService$SafeRunnable run
WARNING: Unexpected throwable from task class com.google.common.util.concurrent.MoreExecutors$ScheduledListeningDecorator$NeverSuccessfulListenableFutureTask: null
java.lang.NullPointerException

Apr 30, 2026 10:07:31 AM org.apache.bookkeeper.common.util.SingleThreadSafeScheduledExecutorService$SafeRunnable run
WARNING: Unexpected throwable from task class com.google.common.util.concurrent.MoreExecutors$ScheduledListeningDecorator$NeverSuccessfulListenableFutureTask: null
java.lang.NullPointerException

Apr 30, 2026 10:08:17 AM org.apache.bookkeeper.common.util.SingleThreadSafeScheduledExecutorService$SafeRunnable run
WARNING: Unexpected throwable from task class com.google.common.util.concurrent.MoreExecutors$ScheduledListeningDecorator$NeverSuccessfulListenableFutureTask: null
java.lang.NullPointerException
```

No stack trace is printed (JVM `-XX:+OmitStackTraceInFastThrow` optimization in effect). To reproduce a full stack trace, add `-XX:-OmitStackTraceInFastThrow` to `server.javaOpts`.

### What is this task?

`SingleThreadSafeScheduledExecutorService` is a BookKeeper internal executor. `NeverSuccessfulListenableFutureTask` is a Guava `MoreExecutors` utility that wraps a `Runnable` submitted to a `ListeningScheduledExecutorService`. The "NeverSuccessful" name means the future was submitted as a fire-and-forget task that never completes normally (i.e., it runs indefinitely or until cancelled). When it throws, the `SafeRunnable` wrapper catches the throwable and logs the warning.

The task that is failing could be:
- A periodic IS heartbeat/status-check task in `IndexingServiceClient`
- A periodic BK ledger management task
- A scheduled IS re-registration check

The NPE was already present at 9:15 AM (before any IS restart) and persisted through the entire run.

---

### Timeline

| Time (CEST) | Event |
|---|---|
| 09:15 AM | NPE already occurring; IS stall (segment back-pressure) resolved via helm upgrade |
| 09:22:06 AM | Server: DNS failure for IS-1 (`UnknownHostException: herddb-indexing-service-1.herddb-indexing-service...`) — IS-1 pod being terminated |
| 09:23:01 AM | Server: DNS failure for IS-0 — IS-0 pod being terminated |
| 09:23:05–06 AM | Both IS pods start; register in ZK successfully |
| 09:23:06 AM | IS-0 log: `Registered indexing service instance: ...instanceId=0` |
| 09:23:06 AM | IS-0: `IndexingServiceEngine started, watermark=(10,12082416), tailerStart=(-1,-1)` |
| 09:23 – 10:15 AM | IS tails herd tablespace commit log (watermark advancing); **zero `AssignIndex` messages received from server** |
| 10:15 AM | `indexing-admin describe-index` on both IS instances: `NOT_FOUND: index not loaded on this instance: vector_bench.vidx` |
| 10:15 AM | `indexing-admin list-indexes` on both IS instances: `(no indexes loaded on this instance)` |
| 10:15 AM | Server restarted (`kubectl delete pod herddb-server-0`) |
| 10:23 AM | Server back up; logs: `bootIndex local herd.vector_bench.vidx ... start VECTOR index vidx in remote mode (IndexingService)` |

### Verbatim server log — gRPC DNS failure (IS-1, IS-0)

```
Apr 30, 2026 9:22:06 AM io.grpc.internal.ManagedChannelImpl$NameResolverListener handleErrorInSyncContext
WARNING: [Channel<11>: (herddb-indexing-service-1.herddb-indexing-service.default.svc.cluster.local:9850)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host herddb-indexing-service-1.herddb-indexing-service.default.svc.cluster.local, cause=java.lang.RuntimeException: java.net.UnknownHostException: herddb-indexing-service-1.herddb-indexing-service.default.svc.cluster.local: Name or service not known

Apr 30, 2026 9:23:01 AM io.grpc.internal.ManagedChannelImpl$NameResolverListener handleErrorInSyncContext
WARNING: [Channel<9>: (herddb-indexing-service-0.herddb-indexing-service.default.svc.cluster.local:9850)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host herddb-indexing-service-0.herddb-indexing-service.default.svc.cluster.local: Name or service not known
```

After IS pods came back online, **no further gRPC success or retry log messages appear** for Channels 9 or 11 in the server log for the remaining 50 minutes.

### IS-0 startup: no AssignIndex received

IS-0 registered in ZK at 09:23:06. The IS-0 log for the next 50 minutes contains only `S3WatermarkStore` watermark polling (for the herd system tablespace), `BookKeeperCommitLog` tailer progress, and ledger events. **No log lines mention `vector_bench`, `vidx`, `AssignIndex`, `createIndex`, or any vector index operation.**

### describe-index confirms no assignment

```
$ indexing-admin describe-index --server herddb-indexing-service-0...:9850 \
    --tablespace 6a37bf785ecb45559ffb804d69ebf129 --table vector_bench --index vidx --json
ERROR: NOT_FOUND: index not loaded on this instance: vector_bench.vidx
```

Same result on IS-1.

### Root cause hypothesis

When the gRPC channels to IS-0 and IS-1 enter `TRANSIENT_FAILURE` due to the DNS outage during the rolling upgrade, the standard gRPC backoff retry mechanism should eventually reconnect. However, **either**:

a) The recurring NPE in `NeverSuccessfulListenableFutureTask` is crashing the IS reconnection/re-assignment task before it can complete the `AssignIndex` gRPC call; **or**

b) The server's `IndexingServiceClient` does not re-send `AssignIndex` when the gRPC channel reconnects after a `TRANSIENT_FAILURE` — only on initial startup and ZK-watcher-triggered discovery events. If the ZK watcher fires but the gRPC is still in TRANSIENT_FAILURE at that moment, the assignment is dropped and never retried.

### Impact

- IS ran for 50+ minutes with the tailer active but no index loaded
- Zero vectors indexed during this period despite active ingestion
- `wait_for_indexes` would have timed out
- A full server pod restart was required to restore normal IS operation
- The IS then had to replay the entire gap in the commit log (ledgers 11–23) from scratch

---

## Suggested fixes

1. **NPE**: Add `-XX:-OmitStackTraceInFastThrow` to server JVM options temporarily to capture the full stack trace and identify the crashing task.

2. **IS re-assignment on reconnect**: In `IndexingServiceClient`, when a gRPC channel transitions from any failure state back to `READY`, re-send all active `AssignIndex` calls for that IS instance. Do not rely solely on ZK discovery events.

3. **IS heartbeat / keepalive**: Add a periodic check in `IndexingServiceClient` that verifies the IS knows about all expected indexes (e.g., calls `ListIndexes` and compares against the local index registry). If a mismatch is found, re-send the missing `AssignIndex` calls. This acts as a self-healing mechanism for any re-registration failures.

4. **Helm rolling-upgrade resilience**: During a rolling IS upgrade (IS-1 terminates before IS-0), the server should detect that an IS re-registered (via ZK watcher on IS-1's new ZK node after restart) and immediately re-register all active indexes on that instance.

---

## Artifacts

- IS-0 log (current): `/home/eolivelli/dev/herddb/herddb-kubernetes/src/main/helm/herddb/examples/gke/reports/is0-current-20260430.log`
- IS-0 log (previous container): `/home/eolivelli/dev/herddb/herddb-kubernetes/src/main/helm/herddb/examples/gke/reports/is0-previous-20260430.log`
- IS-1 log (current): `/home/eolivelli/dev/herddb/herddb-kubernetes/src/main/helm/herddb/examples/gke/reports/is1-current-20260430.log`
- IS-1 log (previous container): `/home/eolivelli/dev/herddb/herddb-kubernetes/src/main/helm/herddb/examples/gke/reports/is1-previous-20260430.log`
- Run log: `/home/eolivelli/dev/tests/run-20260430-093029.log`

## Current values.yaml

```yaml
indexingService:
  replicaCount: 2
  javaOpts: "-Xms28g -Xmx28g -Djava.net.preferIPv4Stack=true --add-modules jdk.incubator.vector -Dio.netty.maxDirectMemory=10737418240 -XX:MaxDirectMemorySize=10g -Dio.netty.allocator.numDirectArenas=8 -Dherddb.commitlog.tailbatchsize=10000 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/herddb/indexdata/heapdump.hprof"
  extraConfig:
    indexing.apply.parallelism: "8"
    indexing.memory.vector.limit: "15032385536"
    server.bookkeeper.ledgers.retention.period: "2100000"
    vector.index.compaction.backpressure.segments: "2147483647"
    vector.index.compaction.maxCount: "2000"
  resources:
    requests:
      memory: "40Gi"
      cpu: "16"
    limits:
      memory: "40Gi"
      cpu: "16"
```

### PR DESCRIPTION
**Pull request by eolivelli**
Fixes #368.

## Problem

After a restart the Indexing Service failed to recover when early BookKeeper
ledgers containing the `CREATE_TABLE` / `CREATE_INDEX` DDL for the indexed
tables had been trimmed by BookKeeper.  The tailer was starting from the
watermark LSN, but `SchemaTracker` was empty — so all subsequent DML entries
were silently dropped (no table/index to apply them to).

Additionally, `PersistentVectorStore` chose its S3 checkpoint path using a
`nanoTime()`-based UUID that changed on every restart, causing the engine to
create a fresh store on S3 instead of re-attaching to the durable checkpoint
from before the restart.

## Changes

| File | Change |
|---|---|
| `herddb/indexing/WatermarkSnapshot.java` | Add `List<Table> tables`, `List<Index> vectorIndexes`, 4-arg constructor, `hasSchema()` |
| `herddb/indexing/LocalWatermarkStore.java` | Serialize/deserialize schema in v1 format; bounds checks (`MAX_TABLES_OR_INDEXES`, `MAX_BLOB_BYTES`) to prevent OOM on corrupt files |
| `herddb/indexing/S3WatermarkStore.java` | Same schema serialization and bounds checks as Local; XXHash64 footer covers schema bytes |
| `herddb/indexing/IndexingServiceEngine.java` | Remove IOException-swallowing around `watermarkStore.load()`; add `installSchemaFromSnapshot()` that pre-populates `SchemaTracker` and creates stores before the tailer starts; embed `_is.store.uuid` in the watermark's index properties; add `vectorStoreIndexUuids` map with correct cleanup on DROP_INDEX/DROP_TABLE/close |
| `herddb/index/vector/AbstractVectorStore.java` | Add `getStoreUUID()` returning `null` (default); eliminates `instanceof PersistentVectorStore` in checkpoint code |
| `herddb/index/vector/PersistentVectorStore.java` | Override `getStoreUUID()` to return `indexUUID` |
| `VECTOR.md` | Document schema snapshot, `_is.store.uuid` story, restart mechanisms |

## Tests

| Class | What it verifies |
|---|---|
| `WatermarkStoreTest` | Round-trip with schema (single/multi table+index), empty-schema round-trip, overwrite with empty, corrupt tableCount/indexCount/blobLen → IOException |
| `WatermarkSchemaRecoveryTest` | Engine restarts from watermark snapshot with correct schema; tailer advances to watermark LSN; post-watermark DDL still applied; DML silently dropped without schema (negative); UUID round-trip via `UUIDReportingVectorStore` |
| `SchemaTrackerTest` | `getAllTables()` and `getAllIndexes()` correctness across CREATE/DROP |
| `S3WatermarkStoreTest` | Monotonicity with schema; hash-covers-schema bytes; corrupt hash rejected |
| `IndexingServiceWithS3E2ETest` | End-to-end: insert + checkpoint + restart with wiped disk → vector counts preserved |

🤖 Implemented by the `pr-worker` agent.

### CODE REVIEW

File: herddb-indexing-service/src/main/java/herddb/indexing/LocalWatermarkStore.java [hunk 1]
```diff
@@ -74,8 +95,45 @@ public WatermarkSnapshot load() throws IOException {
...
+                }
+                int indexCount = dis.readInt();
+                vectorIndexes = new ArrayList<>(indexCount);
+                for (int i = 0; i < indexCount; i++) {
+                    int len = dis.readInt();
+                    byte[] blob = new byte[len];
+                    dis.readFully(blob);
+                    vectorIndexes.add(Index.deserialize(blob));
+                }
+            } catch (EOFException eof) {
```
Comment (eolivelli) [inline herddb-indexing-service/src/main/java/herddb/indexing/LocalWatermarkStore.java]: please fail in this case, this is a corrupted file, it is not expected to support backward compatibilty

File: herddb-indexing-service/src/main/java/herddb/indexing/S3WatermarkStore.java [hunk 2]
```diff
@@ -124,8 +155,39 @@ public WatermarkSnapshot load() throws IOException {
             long ledgerId = din.readZLong();
             long offset = din.readZLong();
             int numInstances = din.readVInt();
+
+            // If more than the 8-byte hash footer remains, the object contains
```
Comment (eolivelli) [inline herddb-indexing-service/src/main/java/herddb/indexing/S3WatermarkStore.java]: we are not supporting backward compatibilti, please remove this handling of compatiiblity
